openapi: 3.0.0
components:
  securitySchemes:
    basicLogin:
      type: http
      scheme: basic
  schemas:
    nameType:
      type: object
      properties:
        full_name:
          description: The name of an organization.
          type: string
          maxLength: 1000
        last_name:
          description: 'For persons, the last or family name.'
          type: string
          maxLength: 100
        first_name:
          description: 'For persons, the first or given name.'
          type: string
          maxLength: 500
        middle_name:
          description: 'For persons, the middle name or initial.'
          type: string
          maxLength: 50
        email:
          description: An email used for contacting this organization or individual.
          type: string
          format: email
          maxLength: 640
        orcid:
          description: 'The ORCID identifying this particular person, author or contributor.'
          type: string
          maxLength: 20
        affiliations:
          description: List any affiliations or labs this person is associated with.
          type: array
          items:
            type: string
            maxLength: 250
      anyOf:
        - required:
            - full_name
        - required:
            - last_name
            - first_name
    contributorType:
      allOf:
        - $ref: '#/components/schemas/nameType'
        - properties:
            contributor_type:
              description: The type of contribution made for this person or organization.
              $ref: '#/components/schemas/contributorTypes'
          required:
            - contributor_type
    contributorTypes:
      type: string
      enum:
        - ContactPerson
        - DataCollector
        - DataCurator
        - DataManager
        - Distributor
        - Editor
        - HostingInstitution
        - Producer
        - ProjectLeader
        - ProjectManager
        - ProjectMember
        - RegistrationAgency
        - RegistrationAuthority
        - RelatedPerson
        - Researcher
        - ResearchGroup
        - RightsHolder
        - Sponsor
        - Supervisor
        - WorkPackageLeader
        - Other
    date:
      type: string
      anyOf:
        - format: year
        - format: yearmonth
        - format: date
        - format: datetime
        - format: year-range
        - format: yearmonth-range
        - format: date-range
        - format: datetime-range
    productTypes:
      type: string
      enum:
        - Audiovisual
        - Collection
        - Dataset
        - Event
        - Image
        - InteractiveResource
        - Model
        - PhysicalObject
        - Service
        - Software
        - Sound
        - Text
        - Workflow
        - Other
    identifierTypes:
      type: string
      enum:
        - ARK
        - arXiv
        - bibcode
        - DOI
        - EAN13
        - EISSN
        - Handle
        - IGSN
        - ISBN
        - ISSN
        - ISTC
        - LISSN
        - LSID
        - PMID
        - PURL
        - UPC
        - URL
        - URN
        - w3id
    relationTypes:
      type: string
      enum:
        - IsCitedBy
        - Cites
        - IsSupplementTo
        - IsSupplementedBy
        - IsContinuedBy
        - Continues
        - IsDescribedBy
        - Describes
        - HasMetadata
        - IsMetadataFor
        - HasVersion
        - IsVersionOf
        - IsNewVersionOf
        - IsPreviousVersionOf
        - IsPartOf
        - HasPart
        - IsReferencedBy
        - References
        - IsDocumentedBy
        - Documents
        - IsCompiledBy
        - Compiles
        - IsVariantFormOf
        - IsOriginalFormOf
        - IsIdenticalTo
        - IsReviewedBy
        - Reviews
        - IsDerivedFrom
        - IsSourceOf
        - IsRequiredBy
        - Requires
        - IsObsoletedBy
        - Obsoletes
    recordType:
      type: object
      properties:
        id:
          description: >-
            Unique identifier for this record for edit purposes. Do not provide for
            new records.
          type: integer
        title:
          description: 'Title of the work, data set, or product.'
          type: string
          maxLength: 500
        sponsoring_organization:
          description: Name of the primary sponsoring organization.
          type: string
          maxLength: 400
        research_organization:
          description: Name of the primary research organization.
          type: string
          maxLength: 400
        accession_number:
          description: >-
            Indicate a client-specific unique identifier if any in your own system.
            May be used in place of specifying ID in future edits if desired.
          type: string
          maxLength: 100
        doi:
          description: >-
            DOI value associated with this record.  Omit for new records to obtain
            initial value.
          type: string
          maxLength: 100
        doi_infix:
          description: Optional DOI infix value used in initial construction of the DOI value.
          type: string
          maxLength: 60
        language:
          description: Primary language of the work.
          type: string
          maxLength: 255
        report_numbers:
          description: Any primary identifying numbers associated with the work.
          type: string
          maxLength: 250
        contract_numbers:
          description: Any contract or award numbers associated with the work.
          type: string
          maxLength: 250
        other_numbers:
          description: Any additional identifying numbers associated with the work.
          type: string
          maxLength: 250
        publisher:
          description: Publisher of the record.
          type: string
          maxLength: 1000
        availability:
          description: >-
            Description of the document's availability, any restrictions on use or
            other information pertinent to its dissemination.
          type: string
          maxLength: 1000
        publication_date:
          description: The date of publication of this information.
          type: string
          format: date
        country:
          description: The country of publication for this work.
          type: string
          maxLength: 1000
        description:
          description: Abstract or description for this work.
          type: string
        site_url:
          description: >-
            The URL to the landing page of this publication, or direct to its full
            text.
          type: string
          format: uri
          maxLength: 250
        product_type:
          description: >-
            Used to specify the type of information contained in this record, one of
            the indicated required values.
          $ref: '#/components/schemas/productTypes'
        product_type_specific:
          description: >-
            Describes the product type in more general terms, to further explain the
            type of information contained within the record.
          type: string
          maxLength: 250
        keywords:
          description: >-
            One or more keywords describing the information in general terms. 
            Multiple values should be semi-colon delimited.
          type: string
          maxLength: 4000
        related_identifiers:
          description: >-
            The set of related identifiers for a given work, indicating type and
            relationship to this work of each identifier.
          type: array
          items:
            type: object
            properties:
              identifier_value:
                type: string
              identifier_type:
                $ref: '#/components/schemas/identifierTypes'
              relation_type:
                $ref: '#/components/schemas/relationTypes'
            required:
              - identifier_value
              - identifier_type
              - relation_type
          minItems: 0
          uniqueItems: true
        authors:
          description: This work's list of authors or creators.
          type: array
          items:
            $ref: '#/components/schemas/nameType'
        contributors:
          description: List of persons or organizations contributing to this work.
          type: array
          items:
            $ref: '#/components/schemas/contributorType'
info:
  title: Interagency Data ID Service API.
  version: 2.0.0
  description: Usage for OSTI Interagency Data ID (IAD) DOI assignment services API.
  contact:
    email: iad@osti.gov
    name: OSTI IAD Service
paths:
  /api/records/query:
    summary: Record search query
    description: Perform various queries against records at OSTI.
    get:
      security:
        - basicLogin: []
      summary: Query records
      description: Perform searches on Interagency Data API Service DOI records.
      operationId: ''
      parameters:
        - in: query
          name: id
          description: The unique record ID value
          schema:
            type: integer
        - in: query
          name: start
          description: 'Starting row offset, from 0 (default 0) in search results'
          schema:
            type: integer
            minimum: 0
            default: 0
        - in: query
          name: rows
          description: Number of desired rows per page of results
          schema:
            type: integer
            default: 10
        - in: query
          name: title
          description: Query within the title of records
          schema:
            type: string
        - in: query
          name: keywords
          description: Query within key words of records
          schema:
            type: string
        - in: query
          name: contributing_organization
          description: Query within contributing organization
          schema:
            type: string
        - in: query
          name: sponsoring_organization
          description: Query within sponsoring organization
          schema:
            type: string
        - in: query
          name: research_organization
          description: Query within research organization
          schema:
            type: string
        - in: query
          name: contract_numbers
          description: Query within contract numbers
          schema:
            type: string
        - in: query
          name: report_numbers
          description: Query within report numbers
          schema:
            type: string
        - in: query
          name: other_numbers
          description: Query within other identifying numbers
          schema:
            type: string
        - in: query
          name: description
          description: Query within description or abstract
          schema:
            type: string
        - in: query
          name: doi
          description: Query DOI values
          schema:
            type: string
        - in: query
          name: availability
          description: Query availability information
          schema:
            type: string
        - in: query
          name: publisher
          description: Query within publisher information
          schema:
            type: string
        - in: query
          name: doi_infix
          description: Query DOI infix values
          schema:
            type: string
        - in: query
          name: accession_number
          description: 'Query accession number, or site unique ID value'
          schema:
            type: string
        - in: query
          name: authors
          description: >-
            Query author information, including names, affiliations, email
            addresses, and ORCID values
          schema:
            type: string
        - in: query
          name: contributors
          description: >-
            Query contributor information, including names, affiliations, email
            addresses, ORCID values, and contribution types
          schema:
            type: string
        - in: query
          name: related_identifiers
          description: Query related identifier values or relation types
          schema:
            type: string
        - in: query
          name: status
          description: Find records with a given status value
          schema:
            type: string
            enum:
              - Pending
              - Error
              - Reserved
              - Registered
              - Deactivated
        - in: query
          name: product_type
          description: Find records by product type
          schema:
            $ref: '#/components/schemas/productTypes'
        - in: query
          name: product_type_specific
          description: Find records of a given specific product type
          schema:
            type: string
        - in: query
          name: site_code
          description: >-
            Find records belonging to a given site code, defaults to user
            account site
          schema:
            type: string
        - in: query
          name: added-after
          description: Find records added after a given date expression
          schema:
            type: string
            format: date
        - in: query
          name: added-before
          description: Find records added before a given date
          schema:
            type: string
            format: date
        - in: query
          name: updated-after
          description: Find records modified after a given date
          schema:
            type: string
            format: date
        - in: query
          name: updated-before
          description: Find records modified before a given date
          schema:
            type: string
            format: date
        - in: query
          name: first-registered-after
          description: Find records initially registered with DataCite after a given date
          schema:
            type: string
            format: date
        - in: query
          name: first-registered-before
          description: Find records initially registered with DataCite before a given date
          schema:
            type: string
            format: date
        - in: query
          name: last-registered-after
          description: Find records most recently registered after a given date
          schema:
            type: string
            format: date
        - in: query
          name: last-registered-before
          description: Find records most recently registered before a given date
          schema:
            type: string
            format: date
        - in: query
          name: published-after
          description: Find records with a date of publication after the given date
          schema:
            type: string
            format: date
        - in: query
          name: published-before
          description: Find records with a date of publication before the given date
          schema:
            type: string
            format: date
        - in: query
          name: all
          description: Find query terms within any indexed record field
          schema:
            type: string
        - in: query
          name: has-doi-infix
          description: Find records that do or do not have DOI infix values
          schema:
            type: boolean
        - in: query
          name: has-related-identifiers
          description: Find records that do or do not have related identifiers
          schema:
            type: boolean
        - in: query
          name: has-accession-number
          description: Find records that do or do not have an accession number value
          schema:
            type: boolean
        - in: query
          name: ever-registered
          description: >-
            Find records that have or have not ever been successfully registered
            with DataCite, and have a live DOI value
          schema:
            type: boolean
        - in: query
          name: sort
          description: Define a sort-by value for search results
          schema:
            type: string
            enum:
              - id
              - doi
              - title
              - added
              - updated
              - first-registered
              - last-registered
              - published
        - in: query
          name: order
          description: 'Define a sort order, ascending or descending for sort order results'
          schema:
            type: string
            enum:
              - asc
              - desc
            default: desc
      responses:
        '200':
          description: Successful search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  start:
                    description: Starting record number of this result set
                    type: integer
                    example: 0
                  rows:
                    description: Number of rows in this result set
                    type: integer
                    default: 10
                    example: 10
                  numFound:
                    description: Total number of results found in this query
                    type: integer
                    example: 855
                  docs:
                    description: Results found in this query page
                    type: array
                    items:
                      $ref: '#/components/schemas/recordType'
        default:
          description: Default error sample response
servers:
  - url: 'https://www.osti.gov/iad2'
    variables: {}
    description: Interagency Data API Service production server
  - url: 'https://www.osti.gov/iad2test'
    variables: {}
    description: Interagency Data API Testing server
